all: morphemeGloss guidedLine text_daylight text_monkeyAndThunder text_lokono text_PlumedSerpent text_prayer text_lokono

morphemeGloss:
	python test_MorphemeGloss.py

guidedLine:
	python test_GuidedLine.py

text_monkeyAndThunder:
	python test_text_MonkeyAndThunder.py

text_daylight:
	python test_text_HowDaylightWasStolen.py

text_PlumedSerpent:
	python test_text_PlumedSerpent.py

# test_text_aktzini.py
text_lokono:
	python test_text_lokono.py

text_prayer:
	python test_text_prayer.py



