all: morphemeGloss line canonicalLine  degenerateLine  wordsAsElementsLine

morphemeGloss:
	python test_MorphemeGloss.py

line:
	python test_Line.py

canonicalLine:
	python test_CanonicalLine.py

degenerateLine:
	python test_DegenerateLine.py

wordsAsElementsLine:
	python test_WordsAsElementsLine.py
