extractAudio:
	python extractAudio.py \
             --xmlfile ../testData/monkeyAndThunder/AYA1_MonkeyandThunder.eaf \
             --audiofile ../testData/monkeyAndThunder/AYA1_MonkeyandThunder-32bit.wav \
             --outputdir monkeyTest


